.\" TODO: regenerate with cargo run -p supazip-cli -- man --out-dir supazip-cli/man
.TH SUPAZIP 1 "June 2026" "supazip 0.4.0" "User Commands"
.SH NAME
supazip \- PeaZip-style archive manager (CLI front-end)
.SH SYNOPSIS
.B supazip
[\fIOPTIONS\fR] \fICOMMAND\fR
.SH DESCRIPTION
SupaZip CLI lets you list, extract, create, and test 7z and ZIP archives.
.PP
Run
.B supazip \-\-help
for the full list of subcommands and flags.
.SH SEE ALSO
Project homepage: https://github.com/your-org/supazip
